analyzer:
  errors:
    file_names: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types 
    - avoid_print
    - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first