name: somnio_code_challenge
description: "Somnio Code Challenge"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  
  bloc_test: ^9.1.7
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/


